[package]
name = "TVTestSDK-rs"
version = "0.0.1"
authors = ["Nep <spica@starry.blue>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.53.1"
