[package]
name = "tvtest"
authors = ["Nep <spica@starry.blue>"]
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.30.0"
features = [
    "alloc",
    "Win32_Foundation",
    "Win32_Globalization",
]
